### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by krisgermann** [txmodxoops/CPanel_Themes#1]
I would like to inquire as to how you might install this?

Directories do not match up with /usr/local/cpanel/base/frontend/ hierarchy

**Comment by txmodxoops** [comment]
Hi kris

What does it mean frontend?

If it's a cpanel this should be a backend !!!

Anyway, if you've noticed, the folder to be overwritten in a version 2.5.7 or 2.5.8 of xoops, is htdocs just overwrite it in localhost

I use WampServer!

I hope I've made clear ideas

I don't recommend to use this beta version in production.

See news: http://xoops.org/modules/news/article.php?storyid=6705
